Refactoring to CSV and OpenStruct. Count movies by month.
vikkanaev/mkdev.me pull request #4
Opened 2020-01-10 17:30 UTC by vikkanaev

Задание: https://mkdev.me/dashboard/user_tasks/11168

Что сделано:
- Парсинг файла переделан на CSV
- Хранение информации о фильмах переделано на OpenStruct
- Добавлен подсчет фильмов за месяц

QnA
Q: Что такое require?
A: Это метод встроенный в язык руби (инстанс метод класса Kernel). Данный метод подгружает руби код из файла или подгружает библиотеку языка/операционной системы.

Q: Как передаются опции при разборе CSV, в виде какого типа данных?
A: В виде хеша.

2020-01-10 18:17 UTC, zverok requested changes

2020-01-10 18:17 UTC, zverok commented on movies.rb
> +}.freeze
Date::MONTHES :)

2020-01-10 18:17 UTC, zverok commented on movies.rb
> +csv = CSV.read(file_name, col_sep: '|')
CSV можно передать массив headers, и он тогда сразу вернёт хеше-подобные структуры, с которыми дальше проще работать

2020-01-10 18:17 UTC, zverok commented on movies.rb
> +  OpenStruct.new(
польза от OpenStruct - в том, что он создаёт почти настоящие объекты, у которых можно вызывать методы imdb_link, title, и т. д.
Если переписать последующий код с этими методами - будет доступно ещё одно упрощение: блоки, вызывающие только один метод без аргументов, можно переписать короче: `sort_by { |i| i.duration }` → `sort_by(&:duration)` (чтобы понять как это работает — смотреть [Symbol#to_proc](https://ruby-doc.org/core-2.6.5/Symbol.html#method-i-to_proc))

2020-01-10 18:17 UTC, zverok commented on movies.rb
> +movies.group_by { |m| m[:release_at].mon }.sort.map { |k, v| puts "#{MONTH[k]}: #{v.count}" }
Кстати, `.each`, а не `.map` :) (В данном случае как бы не важно, но для чтения лучше: если там `map` написано, читатель сразу задумывается «а что мы собирались получить?..»)

2020-01-11 13:46 UTC, vikkanaev commented on movies.rb
> +CSV::Converters[:imdb_list_converter] = lambda { |str, field_info|
Очень сомневаюсь уместно ли тут сождавать собственный конвертор, но как работают стандартные мне не понравилось.

2020-01-11 13:56 UTC, vikkanaev commented on movies.rb
> +  OpenStruct.new(
Да, с записью вида sort_by(&:duration) встречался, но не задумывался как это работает, думал сахар/магия. А это оказывается просто создание прока. Спасибо что обратили внимание на то как это происходит под капотом!

2020-01-11 16:12 UTC, merged