Task 5 starting oop
vikkanaev/mkdev.me pull request #5
Opened 2020-01-12 16:27 UTC by vikkanaev

Задача: https://mkdev.me/dashboard/user_tasks/11169

Что сделано:
- Выполнены все пункты задания
- Дополнительно реализован псевдоним MovieCollection#filter для метода MovieCollection#select. Это сделано по аналогии с одноименными методами в Enumerable
- Дополнительно в классе MovieCollection для инстанс методов sort_by и select добавленна возможность работать с блоком по аналогии с дноименными методами в Enumerable

Что вызывает сомнения:
- Метод MovieCollection::date_safe_parse объявлен при помощи private_class_method. Идея в том, что этот метод не хочется показывать наружу, но есть сомнения насколько это прямой путь, потому что я такого ни где раньше не видел.
- Для метода MovieCollection#stats тоже просится работа с блоком, но я не представляю как из блока получить информацию для какого условия он был вызван (что бы вернуть хеш {условие => количество }. Я нашел варианты когда руби код обращается к своим-же файлам, но этот муть показался мне каким-то сомнительным. В результате блок для stats я реализовать не смог.
- Долго думал где хранить список всех имеющихся в коллекции жанров. Решил что это ответственность экземпляра  MovieCollection. Но как конкретный фильм в этой коллекции узнает об списке жанров? Хотелось получить некий аналог рельсового movie belongs_to movie_collection. Но как это сделать на чистом руби? Решил вставить в каждый экземпляр movie ссылку коллекцию в которую он входит. Не уверен насколько это получилось идеоматично и не раздул ли я объем каждого movie на размер всей коллекции.

2020-01-12 16:50 UTC, zverok requested changes

2020-01-12 16:50 UTC, zverok commented on movie.rb
> +  HEADERS = %w[imdb_link title year country release_at genre duration rate director star_actors].freeze
можно сразу сделать списком символов, CSV это поймёт, а в остальных местах удобнее будет

2020-01-12 16:50 UTC, zverok commented on movie.rb
> +  attr_accessor(*HEADERS.map(&:to_sym))
зачем accessor? кажется, необходимости менять поля уже созданного фильма возникнуть не может

2020-01-12 16:50 UTC, zverok commented on movie.rb
> +  end
решение "фильм должен 'помнить' свою коллекцию совершенно логичное и идиоматичное, но лучше её передавать в конструктор отдельным параметром, чтобы по коду фильма было видно" создаётся из хеша с данными И коллекции-владельца"

2020-01-12 16:50 UTC, zverok commented on movie.rb
> +  end
не, методы интроспекции объекта не должны принимать решение о том чтобы что-то напечатать (а вдруг мы эту библиотеку хотим в веб-приложении использовать? или в десктопном), а только собирать красивую строку, которую клиентский код (demo.rb) уже решает как использовать

2020-01-12 16:50 UTC, zverok commented on movie_collection.rb
> +    key, val = arg.each_pair.first
1. а если фильтров несколько? должно продолжать работать :) year: 2010, country: 'USA'
2. хорошо бы чтобы работало с фильтрами-паттернами: year: 2010..2015, title: /terminator/i - метод === поможет

2020-01-12 16:50 UTC, zverok commented on movie_collection.rb
> +  def stats(arg)
тут к сожалению неправильно понята постановка. должно работать stats(:director) -- возвращая хеш со всеми режиссёрами и кол-вом фильтров каждого

2020-01-12 16:50 UTC, zverok commented on movie_collection.rb
> +  end
лучше бы их закешировать в instance variable (чтобы вычислялись только при первом запросе, ||= поможет)

2020-01-12 16:50 UTC, zverok commented on movie_collection.rb
> +  private_class_method :date_safe_parse
это совершенно логично :)

2020-01-13 10:49 UTC, zverok requested changes

2020-01-13 10:49 UTC, zverok commented on demo.rb
> +movies.sort_by(:duration).last(5).each { |m| puts m.pretty_print }
Интересный момент: если у объекта реализован `to_s`, то всё становится проще:
```ruby
class Foo
  def to_s
    "pretty_foo"
  end
end

puts Foo.new
# печатает "pretty_foo"
puts [Foo.new, Foo.new, Foo.new]
# печатает:
#    pretty_foo
#    pretty_foo
#    pretty_foo
```
Вот поэтому имеет смысл называть метод `to_s` а не как-то иначе :)

2020-01-13 10:49 UTC, zverok commented on movie_collection.rb
> +    arg.each_pair.inject(@movies) { |acc, (key, val)| acc.select { |m| filter_by_type(m, key, val) } }
Учитывая, что оба класса реализовываем мы — тут имеет смысл перенести часть функционала в `Movie`: то есть, если бы у него был метод, например, `matches?(field, pattern)`, тут бы код выглядел аккуратнее.

2020-01-13 10:49 UTC, zverok commented on movie_collection.rb
>    end
Не, надо проще :) Одного обобщённого выражения будет вполне достаточно, если сделать две вещи:
1. Сначала получить плоский массив всех значений из всех фильмов (map+flatten, или flat_map), а потом уже считать кол-во вхождений
2. Для месяца — тоже сделать метод в самом фильме, тупо `month`.

Тогда тут будет одно аккуратное выражение, без `case` и сложных вложенных методов.

2020-01-13 10:49 UTC, zverok commented on movie_collection.rb
>    end
Зачем?..

2020-01-13 10:49 UTC, zverok commented on movie_collection.rb
> +    when :star_actors then /#{val}/i === movie.send(key).to_s
Не. Превращать массив в строку и потом сравнивать — это путь к багам. Например, я прошу фильмы у которых есть актёр "Max Brooks", но не помню как он пишется (max/maxim/maximilian), я использую такой фильтр: `star_actors: /Max.*Brooks/` — НО это заодно и сматчит строку `Max fon Zudow, ..... Mel Brooks`, чего совершенно не нужно.

Лучше сделать простой `if`, учитывающий всего два случая:
* если это поле (вне зависимости от его названия) хранит массив — использовать `any?` (соответствует ли хоть один из элементов массива паттерну)
* если нет — то просто `===`

2020-01-13 12:57 UTC, vikkanaev commented on demo.rb
> +movies.sort_by(:duration).last(5).each { |m| puts m.pretty_print }
Воу! И правда! Спасибо!

2020-01-13 13:39 UTC, vikkanaev commented on movie_collection.rb
> +    arg.each_pair.inject(@movies) { |acc, (key, val)| acc.select { |m| filter_by_type(m, key, val) } }
Да, и правда изящнее

2020-01-13 13:39 UTC, vikkanaev commented on movie_collection.rb
> +    when :star_actors then /#{val}/i === movie.send(key).to_s
ого! класс!

2020-01-13 14:16 UTC, vikkanaev commented on movie_collection.rb
>    end
да, помогло!

2020-01-13 14:27 UTC, zverok requested changes
Осталось со статистикой порядок навести! :)

2020-01-13 14:27 UTC, zverok commented on movie_collection.rb
> +    arr.map { |a| { a => @movies.select { |m| m.matches?(arg, a) }.count } }
Не :) Если не делать строчкой выше `uniq` —  в том массиве достаточно данных, чтобы сразу посчитать статистику — за один проход. А так получается, если у нас 100 разных актёров оказалось в `arr` — мы сто раз проходим по всем 250 фильмам, чтобы спросить у них «а у тебя есть такой актёр»?.. (Хотя мы только что у них уже всё спросили :)))

И, кстати, `flat_map { |m| m.send(arg) }` → `flat_map(&arg)`

2020-01-13 14:55 UTC, zverok commented on movie_collection.rb
> +    @movies.flat_map(&arg).group_by { |e| e }.map { |k, v| { k => v.count } }
`group_by { |e| e }` — как раз для этого случая у руби-объектов есть прекрасный метод `itself` который тупо возвращает тот же объект — так что можно сказать `group_by(&:itself)`.
И ещё есть проблема с результатом — нам бы один хеш {значение → количество, значение → количество, ...}, а он возвращает на самом деле _массив хешей_ из одного элемента ;)

2020-01-13 14:57 UTC, vikkanaev commented on movie_collection.rb
> +    @movies.flat_map(&arg).group_by { |e| e }.map { |k, v| { k => v.count } }
Ааа, {значение → количество, значение → количество, ...} вот теперь понял!

2020-01-13 15:05 UTC, zverok approved these changes

2020-01-13 15:05 UTC, zverok commented on movie_collection.rb
> +    @movies.flat_map(&arg).group_by(&:itself).map { |k, v| [k, v.count] }.to_h
Ага! (Кстати, в руби 2.6 можно просто `to_h { |k, v| [k, v.count] }`)

2020-01-14 07:30 UTC, merged