Turn on rspec, test classes and tune rubocop
vikkanaev/mkdev.me pull request #6
Opened 2020-01-15 15:50 UTC by vikkanaev

2020-01-17 16:40 UTC, zverok requested changes

2020-01-17 16:40 UTC, zverok commented on Gemfile
> +  gem 'factory_bot'
Не нужен :)

2020-01-17 16:40 UTC, zverok commented on spec/.rubocop.yml
> +  Max: 300
Лучше просто выключить, блоки в рспеке любого ж размера могут оказаться.

2020-01-17 16:40 UTC, zverok commented on spec/.rubocop.yml
> +  Enabled: false
А вот этот, кстати, полезный!

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +  let(:input)            { [movie_collection, params] }
Лишнее, можно просто `let(:movie) { described_class.new(movie_collection, params) }`

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +    end
Это бессмысленный контекст. Вы же тут тестируете не свой код, а что Руби правильно работает (если у метода два аргумента, а мы передали 0, будет ошибка). А вот что можно было бы (хотя и не обязательно) протестировать как edge case — что будет если нет какого-то из полей?..

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +          expect { movie.send(key) }.to raise_error(NoMethodError)
И это кстати не очень осмысленно, тут мы тестируем что выражение `attr_reader` правильно сработало (то есть если словами сказать, тут написано «...и у фильма нет методов, которые мы не определяли!»)

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +    let(:err_msg) { "There is no genre #{testing_genre} in #{movie_collection.file_name}" }
Это лучше прям в соответствующий контекст вписать (причём можно прямо в пример без отдельного `let`)

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +      its(:itself) { will raise_error(RuntimeError, err_msg) }
Вот тут начинается больной вопрос! (Можно ничего не менять, но «как обстоят дела» я расскажу).

1. В _большей_ части индустрии, однострочные-примеры-без-decriptions это «фу» — потому и rspec-its (который когда-то был частью рспека) убрали в отдельный гем, и даже что implicit subject это «фу»). (Меньшая часть, включая меня, считает что однострочные примеры — это как раз самый мощный пример использования рспека.)
2. Но! Даже если вы используете rspec-its, одна из важных «фич» — что `its(:something)` это просто шорткат (то есть тривиально переписывается в `it { expect(subject.something).to ...`). И придуманная в нём недавно фича с `will` эту интуцию нарушает — это фича именно rspec-its, хотя и не выглядит таковой.
3. Хуже того, `its(:itself)` выглядит «хаком» (потому что для ВСЕГО кроме will это просто `it { fooo }`, но тут прям почти открытым текстом написано «я использую это, но осознаю что это хак»)

Какие выходы?
1. Продолжаем использовать для учебного проекта, но осознаём что в продакшене так скорее всего попросят не делать
2. Переучиваемся на «многословно но как положено» :)
3. Находим компромиссы (хотя бы не используем для `its(:itself)`; или используем its, но не will)

PS: Я _не_ советую это обычно (хотя мы делаем именно так), просто ради интереса — у меня есть вот такой гем развивающий идеи красивых однострочников: https://github.com/zverok/saharspec. Там эта же проблема решается так:
```ruby
# читается: когда мы вызываем сабжект как блок, то ожидается...
its_block { is_expected.to raise_error(...) }
```
В отличие от подхода с will, оно развивает интуицию исходного rspec-its «its_block это просто **один** шорткат, тривиально переписывается без»

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +      end
Ещё один философский вопрос!
1. В принципе, «обобщённо показать что оно использует `===` от переданного фильтра» это благородная цель
2. Но этот тесты, вообще-то, довольно слабый — а) он плохо показывает _как работают фильтры_ (тест-как-документация) и б) он НЕ тестирует что оно вообще работает. 

Например, вот эта имплементация успешно пройдёт тест:
```ruby
def matches?(field, value)
  value === nil # просто вызываем метод, «чтобы тест был доволен»
  0 # возвращаем какую-то чушь — код на самом деле не работает
end
```

Я бы сказал, что по крайней мере для такого простого класса лучше продемонстрировать/протестировать работу на реальных примерах: то есть проверить что вернёт `matches?(:year, 1994)`, `matches?(:year, 1995)`, `matches?(:year, 1990..2000)`, `matches?(:year, 1990..1991)`.

(А если уж тестировать на «мок-объекте с методом ===», надо тестировать два случая: когда этот метод возвращает true, и когда false)

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +        expect(value).to receive(:any?).with(pattern)
А вот тут даже задумка неверна. Если для паттерна справедливо сказать «то что у паттерна вызовется === — это публичный контракт нашего метода», то КАК ИМЕННО тестируются поля-массивы — вопрос имплементации (например, если вы захотите чтобы этот код работал под руби 2.3, когда `any?` ещё не мог принимать паттерн, вы измените код на `...any? { |val| pattern === val }` — и КОД продолжит работать, а ТЕСТ упадёт, что в корне неверно).
Опять же, достаточно протестировать на реальном случае (а если уж мокать, то тест должен выглядеть как «паттерн должен получить все возможные значения поля, или до тех пор пока не вернёт true» — это даже записывать утомительно)

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +      its(:itself) { will raise_error(ArgumentError) }
Опять тестируем руби а не наш код :) если хочется для этого метода придумать edge cases — лучше проверить, как он себя поведёт с неизвестным полем, или с паттерном который не соответствует типу поля.

2020-01-17 16:40 UTC, zverok commented on spec/movie_spec.rb
> +  end
Перебор. Вполне хватило бы `its(:month) { is_expected.to eq 'October' }` в тестах на создание объекта :)

2020-01-17 16:40 UTC, zverok commented on spec/spec_helper.rb
> +  end
:no_good_man:

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +  let!(:movie_collection)         { described_class.new(file_name) }
почему `let!`?

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +  let!(:instance_variable_movies) { movie_collection.instance_variable_get(:@movies) }
Ненене, это смертный грех :) Тесты тестируют только и исключительно публичный интерфейс, не «что там внутри лежит». Если мы изменим имя внутренней переменной (или скажем способ хранения — станем хранить хешом `{imdb_id => movie}`), все тесты основанные на знаниях о внутренней структуре объекта — упадут.

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +    let(:movie)     { subject.instance_variable_get(:@movies).first }
опять же, никаких `instance_variable_get`

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +        expect(new.instance_variable_get(:@movies)).to(be_any { |e| e.is_a?(Movie) })
`...to all be_a(Movie)` ;)

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +      subject { described_class.new }
Опять тестируем Руби а не свой класс. Лучше проверить как оно поведёт себя при отсутствующем файле.

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +  end
:no_good_man:

2020-01-17 16:40 UTC, zverok commented on spec/movie_collection_spec.rb
> +        end
Нет, никаких «он пошлёт instance_variable такой-то метод». Мы тестируем _публичный интерфейс_. То есть должно быть написано так, как мы бы описали зачем этот метод: «он вернёт все фильмы, отсортированные по...»
Аналогично для остальных методов.

2020-01-20 13:53 UTC, zverok approved these changes
:+1:

2020-01-20 13:53 UTC, zverok commented on spec/movie_collection_spec.rb
> +  it { is_expected.to all be_an_instance_of(Movie) }
`be_a` короче и тот же смысл имеет :)

(Необязательное, просто делюсь на будущее)
1. Кстати, для таких случаев `.and`-объединялка матчеров часто полезна: это ведь по сути _связанные_ тесты: «это должен быть массив фильмов», так что можно записать так: `it { is_expected.to be_an(Array).and all be_a(Movie) }`
2. Но можно пойти ещё и вторым путём — сделать маленький кастомный матчер, это совсем несложно:
```ruby
RSpec::Matchers.define :be_array_of do |instance_class|
  match do |actual|
    expect(actual).to be_an(Array).and all be_a(instance_class)
  end
end
```

2020-01-20 13:53 UTC, zverok commented on spec/movie_collection_spec.rb
>          end
Кстати, забыл сказать раньше, `expect(movies.first).to have_attributes(movie_params)` (или даже прям сюда вписать эти `movie_params`) тоже будет работать :)

2020-01-20 13:53 UTC, zverok commented on spec/movie_collection_spec.rb
> +        expect(list.map(&:country).uniq).to eq ['USA']
можно так (точнее показывает намерения):
```ruby
it { is_expected.to all have_attributes(country: 'USA') }
```

2020-01-20 13:53 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { is_expected.to eq expected_result }
К слову, опять же (здесь и везде) зачастую удобнее читать ожидаемое значение вписанное прямо в тест, а не искать глазами «а что ж у нас там expected result, собственно»

2020-01-20 15:13 UTC, vikkanaev commented on spec/movie_collection_spec.rb
> +  it { is_expected.to all be_an_instance_of(Movie) }
Да, кастомный матчер это прикольно!

2020-01-21 07:45 UTC, merged