Tests for new features
vikkanaev/mkdev.me pull request #7
Opened 2020-01-22 14:29 UTC by vikkanaev

2020-01-22 15:03 UTC, zverok requested changes
Ещё не хватает тестов на то, что когда коллекция загрузится, фильмы окажутся там соответствующих годам типов. А так — можно продолжать!

2020-01-22 15:03 UTC, zverok commented on spec/classic_movie_spec.rb
> +    it { is_expected.to eq('Movie1 - classic movie, director Greatest Director (Movie2, Movie3, Movie4, Movie5, Movie6, Movie7, Movie8, Movie9, Movie10, Movie11)') } # rubocop:disable Layout/LineLeng
К слову, задание подразумевало буквально «(ещё 10 его фильмов в спике)» (то есть количество, а не перечисление — а то длинновата строчка получается) :)

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +    it { is_expected.to be_a(described_class) }
Опять тестируем руби (то есть что `SomeClass.new` создаёт объект желаемого класса). Оно конечно может быть и не всегда так, но по-умолчанию то так :)

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +      its(:balance) { is_expected.to eq 25 }
Кстати, когда мы тестируем метод, который что-то _меняет_, осмысленно использовать матчер `expect {...}.to change`:
```ruby
subject(:pay) { netflix.pay(25) }

it { expect { pay }.to change(netflix, :balance).by(25) }
```

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +    context 'when AncientMovie' do
Тот редкий случай, когда можно разные варианты и без контекстов :) А если с контекстами, то лучше бы так:
```ruby
subject { netflix.how_much?(title) }
context 'when ancient' do
  let(:title) { 'Ancient Crime' }
  it { is_expected.to eq 1 }
end
```

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +        expect(netflix.how_much?('Not existing movie')).to
это не будет работать (экспектейшены которые ожидают какого-то _действия_, должны получать блок, т.е. `expect { ... }.to raise_error`), но вы бы и сами заметили при реализации :)

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +        expect(start_balance - netflix.balance).to eq 1
Вот это вообще идеальный случай для `expect { ... }.to change`

2020-01-22 15:03 UTC, zverok commented on spec/netflix_spec.rb
> +      Timecop.freeze(Time.new(2011, 1, 15, 15, 0)) do
Можно, чтобы не повторяться, заморозить прото в `before` всего дескрайба, один раз

2020-01-22 15:03 UTC, zverok commented on spec/support/matchers/be_act_like_a_movie.rb
> +end
Ну, такой простой матчер наверное не очень достоин выноса в отдельный матчер, разве что для упражнения :)
(Он усложняет чтение, а не упрощает — увидев его в тесте, надо разбираться «а как именно ожидается что должно act это ваше movie... а, просто быть того же класса?.. ну ок...»)

2020-01-22 15:03 UTC, zverok commented on spec/support/shared_examples/movie_cildren.rb
> +end
Кажется, этот shared examples ничего полезного не делает :)
Я бы сказал, что немножко осмысленнее это будет выглядеть если назвать его `shared_context` (и убрать тесты — просто «общий контекст что "есть коллекция, есть аргументы"»... и то полезност не очень очевидна)

2020-01-22 15:03 UTC, zverok commented on spec/theatre_spec.rb
> +      Timecop.freeze(Time.new(2011, 1, 15, 15, 0)) do
Хм. Утро у нас в 3 часа дня? :)
Лучше бы он по текущему времени понимал, который нынче должен быть сеанс.

2020-01-23 18:49 UTC, zverok requested changes

2020-01-23 18:49 UTC, zverok commented on lib/classic_movie.rb
> +    "#{title} - classic movie, director #{director} (his 10 another films)"
так чего ж 10? реальное бы количество (сколько их в коллекции) :)

2020-01-23 18:49 UTC, zverok commented on lib/movie_collection.rb
> +  end
может иметь смысл это сделать методом класса Movie, чтобы коллекция делала Movie.create, не думая о других классах

2020-01-23 18:49 UTC, zverok commented on lib/netflix.rb
> +    when 'NewMovie'     then 5
это можно сделать методом фильма (что удобно, но несколько нарушает разделение ответственности), но если не - такие константные данные удобно сложить в константу-хеш

2020-01-23 18:49 UTC, zverok commented on lib/theatre.rb
> +  end
а хорошо бы всю историю про расписание сложить в константу (или парочку) - во-первых, какой период суток мы считаем утром/днём/вечером, во-вторых, какой части суток какие фильтры соответствуют? тогда будут хорошо разделены "общая логика" (бывают периоды и кинотеатр умеет с ними обращаться) и данные (какие именно периоды бывают), позволяя легко менять последнее

2020-02-03 08:51 UTC, vikkanaev commented on lib/netflix.rb
> +    when 'NewMovie'     then 5
Выбрал константу-хеш

2020-02-03 09:24 UTC, zverok commented on lib/netflix.rb
> +    PRICE[movie.class.to_s]
К слову, а) не обязательно `to_s`, можно в хеше прям классы ключами сделать и б) лучше использовать `.fetch(...)` для таких случаев — тогда если ключ не найден, будет понятная ошибка, а не `nil`

2020-02-03 10:28 UTC, vikkanaev commented on lib/movie_collection.rb
> +  end
Сделал

2020-02-03 12:53 UTC, zverok requested changes

2020-02-03 12:53 UTC, zverok commented on lib/movie.rb
> +  Dir[File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', '*_movie.rb'))].sort.each { |f| require f }
Вообще можно оставить и так, но есть два (противоположных :)) замечания:
1. вообще в большинстве случаев таких упрощений принято избегать. ну типа вроде как `require 'this_movie'`, `require 'that_movie'` и т.д. — это вроде как повторение, но въявную видно, что от чего зависит и что требует, а вот «умный» код требует объяснения в идеале (типа коммента «у нас есть куча наследников, и мы хотим....»)
2. ...но если всё же так делать (это НЕ то чтобы совсем уж плохой вкус, многие избегают, многие используют), Pathname из стандартной библиотеки сильно упрощает жизнь: `Pathname(__FILE__).join('..', 'lib').glob('*_movie.rb').sort.each ...`

2020-02-03 12:53 UTC, zverok commented on lib/movie.rb
> +  private_class_method :movie_klass
:+1:

2020-02-03 12:53 UTC, zverok commented on lib/theatre.rb
> +    evening: OpenStruct.new(key: :genre, value: %w[Drama Horror])
Мне кажется, что достаточно просто хешей для фильтров? т..е. `morning: {class: AncientMovie}`, не?
(Это заодно позволяет при необходимости усложнить расписание, использовав для какого-то из периодов НЕСКОЛЬКО разных фильтров)
И, кстати, для первого фильтра наверное `period: 'ancient'` буде более аккуратно (кинотеатру не надо думать о реальных классах)

2020-02-03 12:53 UTC, zverok commented on lib/theatre.rb
> +    TIMES_OF_DAY.find { |k, _v| k === hour }&.last || :evening
Я бы добавил `:evening` как явный период в `TIME_OF_DAY`, и, как полезное упражнение, сделал бы чтобы эти три периода НЕ покрывали все сутки (что похоже на реальный кинотеатр), с разумным поведением если кинотеатр закрыт.

2020-02-03 12:53 UTC, zverok commented on lib/theatre.rb
> +  def movie_schedule(time)
Лучше бы метод назвать как-нибудь типа `choose_movie` или `guess_movie` (с глаголом — потому что метод что-то «делает», пусть это и просто поиск, а `movie_schedule` выглядит как будто он просто возвращает данные о каком-то расписании).

2020-02-03 12:53 UTC, zverok commented on lib/theatre.rb
> +    %i[morning day evening].select { |t| check_movie(movie, SCHEDULE_RULES[t]) }.first || :never
`select` + `first` — это `detect` ;)
И кстати `nil` в большинстве случаев возвращать более идиоматично для «значение отсутствует», чем спец.значение того же типа.

2020-02-03 13:41 UTC, vikkanaev commented on lib/movie.rb
> +  private_class_method :movie_klass
Спасибо. А можно чуть более развернуто пожалуйста? В таком виде я не смогу ассимилировать, потому что не понимаю что именно вызвало похвалу.

2020-02-03 15:15 UTC, vikkanaev commented on lib/theatre.rb
> +    evening: OpenStruct.new(key: :genre, value: %w[Drama Horror])
Исправил

2020-02-03 15:15 UTC, vikkanaev commented on lib/theatre.rb
> +    TIMES_OF_DAY.find { |k, _v| k === hour }&.last || :evening
исправил

2020-02-03 15:27 UTC, vikkanaev commented on lib/movie.rb
> +  Dir[File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', '*_movie.rb'))].sort.each { |f| require f }
выбрал множественный require

2020-02-03 16:14 UTC, zverok commented on lib/movie.rb
> +  private_class_method :movie_klass
Корректно выбранные и минимально воплощённые решения небольшой, но раньше не встречавшейся (в нашем курсе) проблемы :)

2020-02-03 16:21 UTC, zverok approved these changes

2020-02-03 16:21 UTC, zverok commented on lib/theatre.rb
> +    filter.each_pair.inject([movie]) { |acc, (key, val)| acc.select { |m| m.matches?(key, val) } }.any?
На самом деле у нас же `any?` и `all?` умеют принимать блоки, поэтому здесь есть намного более минимальное решение: `filter.all? { кино соответствует фильтру }`

2020-02-03 16:21 UTC, zverok commented on lib/theatre.rb
> +    movie_collection.filter(filter).first
Тут кстати (факультативно) можно задуматься о том, чтобы каждый раз показывать не первое, а _случайное_ кино соответствующее фильтру (там будет интересный челлендж с тем, как это протестировать)

2020-02-03 16:21 UTC, zverok commented on lib/theatre.rb
> +    filter = SCHEDULE_RULES[operating_mode(time.hour)]
В таких случаях (мы уверены, что ключ должен найтись) лучше использовать `Hash#fetch` — который бросает понятное исключение, если ключ не нашёлся. Это может помочь при рефакторинге (например, мы добавили везде новый период `:night`, или скажем `:sunday`, а в `SCHEDULE` его добавить забыли — или тупо опечатка, и туда добавлен ключ `:nigt`). С `[]` хеш вернёт `nil`, и ошибка будет в глубине `filter`, с непонятным сообщением «у nil нет какого-то метода», а с `fetch` — осмысленное сообщение «в хеше нет такого ключа»

2020-02-03 17:19 UTC, vikkanaev commented on lib/theatre.rb
> +    filter.each_pair.inject([movie]) { |acc, (key, val)| acc.select { |m| m.matches?(key, val) } }.any?
исправил

2020-02-05 08:43 UTC, merged